###Config###
title: Duck Pizza
email: hi@duck.pizza
url: https://duck.pizza
description: "Zac's super cool portfolio and blog website thing"
keywords: "duck pizza, Zac Lucarelli"
meta_author: Zac Lucarelli

# Google webmaster tools
google_verify: 5iyhmJPvXUukBZoZtl9OpHSygvt7ONVYtazp7e4p9oE

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Build settings
markdown: kramdown
permalink: pretty

#font fix
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

#Collections
collections:
    games:
        output: true
    other:
        output: true

####Theme###

# Color settings (hex-codes without the leading hash)
color:
  primary: 26014d #rgb(58, 0, 119)
  primary-rgb: "58, 0, 119"
  primary-dark: 1d003c #1d003c
  primary-light: 291876 #291876
  secondary: fc8726 #fc8726    
  secondary-dark: fc8726 #fc8726   
  third: e7cfff #e7cfff
  
  link: ffffff #ffffff   
  

# Icon links in the header bar,
# icon refers to the icomoon font name
social:
  - icon: twitter
    url: http://twitter.com/duckPizza_
  - icon: github
    url: http://github.com/chikanz
  - icon: itch
    url: https://snootboop.itch.io/
  - icon: youtube
    url: https://www.youtube.com/channel/UC_I02j_siBz4y7L06nBjjiA

#nav modifier
navmulti: 1.5

#Overflow settings
#Cap posts at collection index, (i.e. games is capped at X, creative at Y) make sure to set to same length as collections
concat: [1, 5, 2]


    
    